### ISSUE TITLE
Feature: Youtube 

### ISSUE THREAD

**Issue by TheRealMrKam** [DeathWrench/BestestTVMod#3]
Hello, any way to also add  the functionality of this mod: https://thunderstore.io/c/lethal-company/p/KoderTeh/Television_Controller/ ?

**Comment by DeathWrench** [comment]
If I can implement this without breaking everything else. I don't like chat commands, so I'll have it work differently. Probably read the links from the config file instead.

**Comment by TheRealMrKam** [comment]
Can it read it if it's changed while in game ?

**Comment by DeathWrench** [comment]
~~Off the top of my head, it won't since it'll be appended to the list of videos to load, which only gets initialized when the game starts. It's just how the mod works, and I fear adding something that messes with that list is gonna break a bunch of stuff.~~
I took a look at how that mod works and I don't like the idea of adding something that has to download a .exe in order to work:
![image](https://github.com/DeathWrench/BestestTVMod/assets/45341450/624a8cff-6c40-4d6c-b444-21ceac801b00)
I could use something like this: https://thunderstore.io/c/lethal-company/p/Lordfirespeed/YoutubeDLSharp/
Make a separate mod for downloading YouTube videos using it and put everything it downloads into a Television Videos folder. Either way you'd still have to restart the game probably. Since that mod just downloads YouTube videos in the same way anyways. I'll see what I can do though.

**Comment by TheRealMrKam** [comment]
It's ok dude thanks for checking it out !  The whole point for youtube is being able to watch things that haven't being setup before. Sometimes i use your mod but i mostly use the youtube one (even if buggy sometimes) i can continue doing that it's ok !

**Comment by DeathWrench** [comment]
I've managed to do it to where it updates the video list after downloading the video:
![image](https://github.com/DeathWrench/BestestTVMod/assets/45341450/cc6761c0-991b-44ec-bf51-d1fa4f6355f5)
It can download full playlists as well. Will post repository and to Thunderstore soon.

**Comment by TheRealMrKam** [comment]
Oh nice ! Thanks , i'll try it out !

**Comment by TheRealMrKam** [comment]
I don't seem to be able to put the tv on when clicking on it, gives me an error in console, here is the log :

[LogOutput.log](https://github.com/DeathWrench/BestestTVMod/files/14695840/LogOutput.log)

(Doesn't work with always on either)

**Comment by DeathWrench** [comment]
I've released a new version of BestestTVMod. Tell me if this fixes it.

**Comment by TheRealMrKam** [comment]
No, still can't put it on :/

**Comment by DeathWrench** [comment]
Go into r2modman/Thunderstore Mod Manager settings and copy/paste the dependency list here.

**Comment by TheRealMrKam** [comment]
I don't use a mod manager, is there another dependency expect Bepinex for BestestTVMod ?

**Comment by DeathWrench** [comment]
You need this for the YoutubeDownloader: https://thunderstore.io/c/lethal-company/p/Lordfirespeed/YoutubeDLSharp/
A possible issue could be that I've set it up to look for the folder that it installs with mod managers.
```static string pluginPath = Paths.PluginPath + Path.DirectorySeparatorChar.ToString() + "DeathWrench-YoutubeDownloader";```
If you place the files in here:
plugins/DeathWrench-YoutubeDownloader
Does it work?

**Comment by TheRealMrKam** [comment]
It seems it's because i had no video in the "Television videos" folder
 I'll retry with the youtube extension now

**Comment by TheRealMrKam** [comment]
It works if i put the files directly into plugin/ ! but not into subfolders, any way to make it work with any subfolders ? 
Can we have an option in config for auto deleting videos if you quit the game ?

Also i was wondering, what happen to other players, does it download the video for them too ?

**Comment by DeathWrench** [comment]
This is how I have mine set up:
![image](https://github.com/DeathWrench/BestestTVMod/assets/45341450/33f34807-7300-46c6-b2db-8c82c1015c43)
![image](https://github.com/DeathWrench/BestestTVMod/assets/45341450/7d2f8bb1-cf2c-4cde-8318-a656512ddb7b)
Don't know what you mean by subfolders. It should be checking those too.
No it doesn't download the video for other players.

**Comment by TheRealMrKam** [comment]
My bad it does work on subfolders ! (was pressing the wrong button before haha)

So i download the video and others can see it too right ?

**Comment by DeathWrench** [comment]
> So i download the video and others can see it too right ?

No, they would also need to have the video downloaded in order to see it. Not only that, but you'd need the same videos/config settings for it to be synced up properly. I'm pretty sure, if you change the channel, it only changes it for you. Though I could be wrong about that.

**Comment by TheRealMrKam** [comment]
Oh i see, because in television controler it was synced with others

**Comment by DeathWrench** [comment]
Not going to do that, since it's outside of the scope of what this mod is trying to do. ie. TVLoader + LethalTVManager + config options.
