### ISSUE TITLE
How to upload mod with my mp4 files to Thunderstore?

### ISSUE THREAD

**Issue by Th3GamingDonkey** [DeathWrench/BestestTVMod#5]
So I've been trying litterally everything and nothing works. Tvloader, Customtelevision by flipmods and even taking someone elses mod with mp4 videos and just changing the mp4 files with mine but every time I try to upload a mod, it just says (Not found). I came across the Bestest television mod and now I really want to make this mod work. 

What I want to do is to upload a mod that has the mp4 videos so my friends can download the mod and get all the mp4 videos. 

How do I do that using this mod? 

also 2nd question is does everyone get the same video when you have shuffle on or does everyone get different videos?

**Comment by DeathWrench** [comment]
Same as making a pack for TVLoader
- manifest.json should look something like this:
```
{
    "name": "YourTVModPackNameHere",
    "version_number": "1.0.0",
    "website_url": "",
    "description": "Short description appears when searching the mod on thunderstore.",
    "dependencies": [
        "DeathWrench-BestestTelevisionMod-1.2.7"
    ]
}
```
- Next you make a README.md type some text in it.
- Add a icon.png with 256x256 dimensions.
- Add Television Videos folder with .mp4s in it. 
- .zip everything up.
- Upload it to Thunderstore.

No, doesn't sync when shuffling, except if you both only had 1 video lol.

#### If all else fails, but the videos are on youtube you can make a playlist and download them in game using the [YoutubeDownloader](https://thunderstore.io/c/lethal-company/p/DeathWrench/YoutubeDownloader/) mod
